FROM golang:1.14-alpine AS build
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY . .
RUN go build -tags musl -o main

FROM alpine AS run
WORKDIR /app
COPY --from=build /app/main .
ENTRYPOINT ./main