FROM ubuntu AS run
ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y git golang-go gcc musl-dev python2 tar wget xdg-utils xz-utils
RUN mkdir -p /opt/calibre
RUN wget https://download.calibre-ebook.com/linux-installer.sh && chmod +x linux-installer.sh && ./linux-installer.sh
WORKDIR /app
COPY . .
RUN go build -mod vendor -o main
ENTRYPOINT ./main